In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
!rm -rf /content/wesad_repo
!git clone https://github.com/it95-6/wesad.git /content/wesad_repo

Cloning into '/content/wesad_repo'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20 (delta 2), reused 20 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (20/20), 16.05 KiB | 16.05 MiB/s, done.
Resolving deltas: 100% (2/2), done.


In [3]:
import os
import sys
from pathlib import Path
import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

PROJECT_ROOT = Path("/content/drive/MyDrive/WESAD_project")
REPO_ROOT = Path("/content/wesad_repo")
DATA_ROOT = PROJECT_ROOT / "data"
OUTPUT_ROOT = PROJECT_ROOT / "outputs"

os.environ["WESAD_PROJECT_ROOT"] = str(PROJECT_ROOT)
os.environ["WESAD_REPO_ROOT"] = str(REPO_ROOT)
os.environ["WESAD_DATA_ROOT"] = str(DATA_ROOT)
os.environ["WESAD_OUTPUT_ROOT"] = str(OUTPUT_ROOT)
os.environ["WESAD_NPZ_PATH"] = str(DATA_ROOT / "wesad_windows.npz")
os.environ["WESAD_NUM_WORKERS"] = "2"
os.environ["WESAD_REQUIRE_CUDA"] = "1"
os.environ["WESAD_USE_AMP"] = "1"

print("npz exists:", Path(os.environ["WESAD_NPZ_PATH"]).exists())


CUDA available: True
GPU: Tesla T4
npz exists: True


In [7]:
%cd /content/wesad_repo
!pip install -q torch torchvision torchaudio scikit-learn seaborn matplotlib numpy pandas
!python -m research.train_cnn

/content/wesad_repo
Using device: cuda
GPU: Tesla T4
Loaded raw NPZ: X=(5770, 21000, 2), y=(5770,)
Train: (2096, 2, 21000), (2096,)
Val  : (300, 2, 21000), (300,)
Test : (600, 2, 21000), (600,)
[Epoch 01/20] train_loss=1.2832 train_acc=0.4008 train_f1=0.2930 val_loss=1.2706 val_acc=0.4133 val_f1=0.2797
[Epoch 02/20] train_loss=1.2115 train_acc=0.4838 train_f1=0.3526 val_loss=1.1471 val_acc=0.5700 val_f1=0.4316
[Epoch 03/20] train_loss=1.1642 train_acc=0.5215 train_f1=0.3922 val_loss=1.1935 val_acc=0.5333 val_f1=0.4001
[Epoch 04/20] train_loss=1.1295 train_acc=0.5277 train_f1=0.3872 val_loss=1.0753 val_acc=0.5667 val_f1=0.4091
[Epoch 05/20] train_loss=1.1172 train_acc=0.5401 train_f1=0.4188 val_loss=1.0267 val_acc=0.6267 val_f1=0.4785
[Epoch 06/20] train_loss=1.0788 train_acc=0.5496 train_f1=0.4238 val_loss=1.1334 val_acc=0.5700 val_f1=0.4239
[Epoch 07/20] train_loss=1.0640 train_acc=0.5530 train_f1=0.4341 val_loss=1.4877 val_acc=0.4833 val_f1=0.3487
[Epoch 08/20] train_loss=1.1090 trai

In [8]:
!python -m research.evaluate_cnn

Using device: cuda
GPU: Tesla T4
=== Evaluation ===
Accuracy : 0.6583
Macro F1 : 0.5221
Confusion matrix:
[[211   3   0  21]
 [ 23  98   0  13]
 [ 49   8   0  17]
 [ 61  10   0  86]]
Classification report:
              precision    recall  f1-score   support

           0     0.6134    0.8979    0.7288       235
           1     0.8235    0.7313    0.7747       134
           2     0.0000    0.0000    0.0000        74
           3     0.6277    0.5478    0.5850       157

    accuracy                         0.6583       600
   macro avg     0.5162    0.5442    0.5221       600
weighted avg     0.5884    0.6583    0.6116       600

Figure(600x500)
Saved figure to: /content/drive/MyDrive/WESAD_project/outputs/figures/cnn1d_ecg_eda_confusion_matrix.png
